### ISSUE TITLE
No config file is generated

### ISSUE THREAD

**Issue by Pannoniae** [Lothrazar/WorldPortals#1]
Minecraft Version: 1.16.5

Forge Version: 36.1.0

Mod Version: 1.1.0

Single Player or Server: Singleplayer

Describe problem (what you were doing; what happened; what should have happened):
Expected config file to generate. It didn't generate in mcfolder/config.

**Comment by Pannoniae** [comment]
Nevermind, I'm just retarded. It's named "worldportals" instead of lattice world portals as I would have expected. Stupid user error :)

**Comment by Lothrazar** [comment]
Lol no worries
